<script lang="ts">
  import {tick} from 'svelte';import ContentSearchBar from '$lib/components/content/ContentSearchBar.svelte';import ContentList from '$lib/components/content/ContentList.svelte';import ContentDetailView from '$lib/components/content/ContentDetail.svelte';import type{ContentBrowserState}from'$lib/state/content-browser';import type{ContentSearchState}from'$lib/state/content-search';import type{BrowseScope,ContentDetail,ContentKind,ContentSummary}from'$lib/types/content'
  interface Props{browser:ContentBrowserState;search:ContentSearchState;selectedDetail:ContentDetail|null;detailLoading:boolean;pendingDeleteIds?:string[];onSearch:(q:string)=>void;onClearSearch:()=>void;onSelect:(id:string|null)=>void;onSetKind:(kind:ContentKind|null)=>void;onReorder:(ids:string[])=>Promise<void>;onToggleSaved:(item:ContentSummary)=>void;onCopy:(item:ContentSummary)=>void;onDelete:(item:ContentSummary)=>void;onCreateText:()=>void;onDetailChanged:(id:string)=>Promise<void>;onNotify:(m:string,k?:'success'|'error')=>void}
  let{browser,search,selectedDetail,detailLoading,pendingDeleteIds=[],onSearch,onClearSearch,onSelect,onSetKind,onReorder,onToggleSaved,onCopy,onDelete,onCreateText,onDetailChanged,onNotify}:Props=$props();let scroll:HTMLDivElement;let wasSearching=$state(false);let preSearchSelection=$state<string|null>(null);let scopeScrollTop=$state<Record<BrowseScope,number>>({temporary:0,all:0,saved:0})
  const searching=$derived(search.query.trim().length>0);const items=$derived(searching?search.hits.map(h=>h.summary):browser.items);const selectedId=$derived(searching?search.selectedId:browser.selectedId);const reorderable=$derived(!searching&&browser.scope!=='all');
  function searchInput(q:string){if(!wasSearching&&q.trim()){scopeScrollTop[browser.scope]=scroll?.scrollTop??0;preSearchSelection=browser.selectedId;wasSearching=true}onSearch(q)}
  async function clear(){onClearSearch();wasSearching=false;await tick();if(preSearchSelection)onSelect(preSearchSelection);if(scroll)scroll.scrollTop=scopeScrollTop[browser.scope]}
  function select(id:string|null){onSelect(id)}
</script>
<div class="workspace">
  <ContentSearchBar query={search.query} selectedKind={browser.kind} searching={search.phase==='searching'} onSearch={searchInput} onClear={clear} {onSetKind}/>
  <div class="context"><span>{searching?`${items.length} 个搜索结果`:browser.scope==='temporary'?'临时内容会按设置自动清理':`${items.length} 项内容`}</span>{#if browser.scope==='temporary'&&!searching}<button type="button" onclick={onCreateText}>＋ 新建文本</button><span>也可直接粘贴或拖入文件</span>{/if}</div>
  <div class="body" class:detail-open={!!selectedDetail||detailLoading}>
    <div class="scroll" data-testid="content-scroll" bind:this={scroll} onscroll={()=>{if(!searching)scopeScrollTop[browser.scope]=scroll.scrollTop}}>
      {#if items.length}<ContentList {items} {selectedId} {reorderable} busyIds={pendingDeleteIds} onSelect={(id)=>select(id)} {onReorder} {onToggleSaved} {onCopy} {onDelete}/>
      {:else}<div class="empty"><strong>{searching?'没有匹配内容':browser.scope==='temporary'?'收纳还是空的':browser.scope==='saved'?'还没有收藏内容':'还没有内容'}</strong><span>{searching?'尝试更短的关键词或清除类型筛选':'粘贴文字、截图或拖入文件即可开始'}</span></div>{/if}
    </div>
    {#if detailLoading}<div class="detail loading" role="status">正在载入详情…</div>{:else if selectedDetail}<div class="detail"><ContentDetailView detail={selectedDetail} resetToken={selectedDetail.summary.id} onClose={()=>select(null)} onChanged={onDetailChanged} {onNotify} onDelete={()=>onDelete(selectedDetail.summary)} onToggleSaved={()=>onToggleSaved(selectedDetail.summary)}/></div>{/if}
  </div>
</div>
<style>.workspace{min-height:0;flex:1;display:flex;flex-direction:column;overflow:hidden}.context{min-height:2rem;display:flex;align-items:center;gap:.55rem;padding:.3rem .65rem;color:var(--text-muted);font-size:var(--font-xs,.65rem);border-bottom:1px solid var(--border-subtle)}.context button{margin-inline-start:auto;min-height:1.9rem;border:1px solid var(--color-primary);border-radius:var(--radius-md);background:color-mix(in srgb,var(--color-primary) 12%,var(--surface-1));color:var(--text-primary);font:inherit;cursor:pointer}.body{min-height:0;flex:1;display:grid;grid-template-columns:minmax(0,1fr);position:relative}.scroll{min-width:0;overflow:auto;padding:.5rem}.detail{position:absolute;inset:0;z-index:10;overflow:hidden;background:var(--surface-0)}.loading{display:grid;place-items:center;color:var(--text-muted)}.empty{min-height:12rem;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:.35rem;text-align:center;color:var(--text-muted)}.empty strong{color:var(--text-primary)}@media(min-width:680px){.body.detail-open{grid-template-columns:minmax(280px,.9fr) minmax(340px,1.1fr)}.body.detail-open .detail{position:static;border-left:1px solid var(--border-subtle)}}@media(max-width:300px){.context{align-items:flex-start;flex-wrap:wrap}.context button{margin-inline-start:0}.scroll{padding:.3rem}}</style>
