<script lang="ts">
  import type { BrowseScope } from '$lib/types/content';import{dockApi}from'$lib/api/dock';import{messages}from'$lib/i18n'
  interface Props{currentView:BrowseScope|'settings';onNavigate:(view:BrowseScope)=>void;onToggleSettings:()=>void;onMinimize:()=>void}
  let{currentView,onNavigate,onToggleSettings,onMinimize}:Props=$props();let alwaysOnTop=$state(true)
  async function togglePin(){try{alwaysOnTop=await dockApi.toggleAlwaysOnTop()}catch{}}
  async function drag(e:MouseEvent){if((e.target as HTMLElement).closest('button'))return;e.preventDefault();try{const{getCurrentWindow}=await import('@tauri-apps/api/window');await getCurrentWindow().startDragging()}catch{}}
  const scopes:[BrowseScope,string][]=$derived([['temporary',messages.workspace.scope.temporary],['all',messages.workspace.scope.all],['saved',messages.workspace.scope.saved]])
</script>
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="top" onmousedown={drag}>{#each scopes as [scope,label]}<button type="button" class:active={currentView===scope} aria-current={currentView===scope?'page':undefined} onclick={()=>onNavigate(scope)}>{label}</button>{/each}<span class="spacer"></span><button type="button" class:active={alwaysOnTop} aria-label={alwaysOnTop?messages.nav.unpin:messages.nav.pin} onclick={togglePin}>⌖</button><button type="button" class:active={currentView==='settings'} onclick={onToggleSettings}>{messages.nav.settings}</button><button type="button" aria-label={messages.nav.minimize} onclick={onMinimize}>—</button></div>
<style>.top{min-height:2.5rem;display:flex;align-items:stretch;gap:.12rem;padding:.2rem .3rem;border-bottom:1px solid var(--border-subtle);cursor:move;user-select:none}.top button{min-width:0;min-height:2.1rem;padding:.3rem .55rem;border:1px solid transparent;border-radius:var(--radius-md);background:none;color:var(--text-muted);font:inherit;font-size:max(var(--font-sm,.68rem),.68rem);white-space:nowrap;cursor:pointer}.top button:nth-child(-n+3){flex:1}.top button.active{border-color:color-mix(in srgb,var(--color-primary) 35%,transparent);background:color-mix(in srgb,var(--color-primary) 12%,transparent);color:var(--text-primary)}.spacer{flex:.15}.top button:focus-visible{outline:2px solid var(--color-primary);outline-offset:1px}@media(max-width:300px){.top{padding:.1rem}.top button{padding:.25rem .3rem}.spacer{display:none}}</style>
